spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: joao
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      bibernate.format_sql: true